version: 2.1
jobs:
  build:
    working_directory: ~/web-monitoring-processing
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - processing-{{ arch }}-v1-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
            - processing-{{ arch }}-v1-

      # Bundle install dependencies
      - run:
          name: Install Dependencies
          command: |
            echo 'Creating virtualenv...'
            python -m venv venv
            echo 'Created virtualenv'
            . venv/bin/activate
            echo 'Activated virtualenv'
            pip install --upgrade pip
            echo 'Upgraded pip'
            pip install wheel
            echo 'Wheel'
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install .

      # Store bundle cache
      - save_cache:
          key: processing-{{ arch }}-v1-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - venv

      - run:
          name: Tests
          command: |
            . venv/bin/activate
            coverage run run_tests.py -v web_monitoring/tests/
      - run:
          name: Coverage
          command: |
            . venv/bin/activate
            coverage report -m
      - run:
          name: Code linting
          command: |
            . venv/bin/activate
            pyflakes web_monitoring
      - run:
          name: Build docs
          command: |
            . venv/bin/activate
            cd docs && make html

  build_docker:
    machine: true
    steps:
      - checkout
      - run: |
          docker build -t envirodgi/processing:$CIRCLE_SHA1 .
      - run:
          name: Save Image
          command: |
            mkdir /tmp/workspace
            docker save --output /tmp/workspace/docker-image envirodgi/processing:$CIRCLE_SHA1
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker-image

  publish_docker:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Built Docker Image
          command: docker load --input /tmp/workspace/docker-image
      - run:
          name: Re-tag Image
          command: docker image tag envirodgi/processing:$CIRCLE_SHA1 envirodgi/processing:latest
      - run:
          name: Publish to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push envirodgi/processing:$CIRCLE_SHA1
            docker push envirodgi/processing:latest

workflows:
  build:
    jobs:
      - build
      # The docker image is currently focused on the diff server, which now
      # lives in the web-monitoring-diff project and will be published there.
      # The current docker image should be considered deprecated and will no
      # longer be updated.
      #
      # We're keeping this code around for future images based around the other
      # scripts here for possible use with things like AWS Batch.
      # - build_docker
      # - publish_docker:
      #     requires:
      #       - build
      #       - build_docker
      #     filters:
      #       branches:
      #         only:
      #           - release
