version: 2.1

parameters:
  primary-python-version:
    type: string
    default: "3.10.16"

commands:
  setup_pip:
    description: "Set Up Dependencies"
    parameters:
      python-version:
        type: string
      install-docs:
        description: Install docs dependencies
        type: boolean
        default: false
      install-extras:
        type: string
        default: ''
    steps:
      - checkout
      - restore_cache:
          keys:
            - processing-{{ arch }}-<< parameters.python-version >>-v5-{{ checksum "pyproject.toml" }}
            - processing-{{ arch }}-<< parameters.python-version >>-v5-

      - run:
          name: Install Dependencies
          command: |
            extras='test'
            if [[ '<< parameters.install-docs >>' == 'true' ]]; then
              extras="${extras},docs"
            fi
            if [[ -n '<< parameters.install-extras >>' ]]; then
              extras="${extras},<< parameters.install-extras >>"
            fi

            python -m venv ~/venv
            . ~/venv/bin/activate
            pip install --upgrade pip
            pip install ".[${extras}]"

      - save_cache:
          key: processing-{{ arch }}-<< parameters.python-version >>-v5-{{ checksum "pyproject.toml" }}
          paths:
            - venv

jobs:
  test:
    parameters:
      python-version:
        type: string
      extras:
        type: string
        default: ''
    working_directory: ~/web-monitoring-processing
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - checkout
      - setup_pip:
          python-version: << parameters.python-version >>
          install-extras: << parameters.extras >>
      - run:
          name: Tests
          command: |
            . ~/venv/bin/activate
            coverage run run_tests.py -v web_monitoring/tests/
      - run:
          name: Coverage
          command: |
            . ~/venv/bin/activate
            coverage report -m

  lint:
    working_directory: ~/web-monitoring-processing
    docker:
      - image: cimg/python:<< pipeline.parameters.primary-python-version >>
    steps:
      - checkout
      - setup_pip:
          python-version: << pipeline.parameters.primary-python-version >>
      - run:
          name: Code linting
          command: |
            . ~/venv/bin/activate
            pyflakes web_monitoring

  docs:
    working_directory: ~/web-monitoring-processing
    docker:
      - image: cimg/python:<< pipeline.parameters.primary-python-version >>
    steps:
      - checkout
      - setup_pip:
          python-version: << pipeline.parameters.primary-python-version >>
          install-docs: true
      - run:
          name: Build docs
          command: |
            . ~/venv/bin/activate
            cd docs && make html

  build_docker:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run: |
          docker build --target release --tag envirodgi/processing:$CIRCLE_SHA1 .
      - run:
          name: Save Image
          command: |
            mkdir /tmp/workspace
            docker save --output /tmp/workspace/docker-image envirodgi/processing:$CIRCLE_SHA1
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker-image

  publish_docker:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Built Docker Image
          command: docker load --input /tmp/workspace/docker-image
      - run:
          name: Re-tag Image
          command: docker image tag envirodgi/processing:$CIRCLE_SHA1 envirodgi/processing:latest
      - run:
          name: Publish to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push envirodgi/processing:$CIRCLE_SHA1
            docker push envirodgi/processing:latest

workflows:
  build:
    jobs:
      - test:
          matrix:
            parameters:
              python-version: ["3.10", "3.11", "3.12", "3.13"]
              extras: ["", "cchardet"]
            exclude:
              - python-version: "3.13"
                extras: "cchardet"
      - lint
      - docs
      - build_docker
      - publish_docker:
          requires:
            - test
            - lint
            - build_docker
          filters:
            branches:
              only:
                - release
